/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `cpp-library`
}
library {
    targetMachines.add(machines.linux.x86_64) 
    baseName.set(rootProject.name)
}
version = "1.0.0"